//ARQUIVO DE REFERENCIA PARA OS SERVICES
//SEMPRE QUE UM SERVICE FOR CRIADO, ELE DEVERÁ SER IMPORTADO E EXPORTADO AQUI COMO SEGUE O EXEMPLO DE TESTE

const teste = require('./teste')

module.exports = {
  teste
}