partidas = {
  partidas: [
    {
      data: "2019-11-20 15:00:00",
      categoria: "LAN",
      idCampeonato: 1,
      idMapa: 3,
      idEquipeA: 1,
      idEquipeB: 2,
      melhorDe: 1,
      numeroPartida: 1,
      prorrogacao: false,
      partidaEncerrada: true,
      pontuacaoEquipeA: 16,
      pontuacaoEquipeB: 12,
      idEquipeVitoria: 1,
      idEquipeDerrota: 2,
    },
    {
      data: "2019-11-20 16:00:00",
      categoria: "LAN",
      idCampeonato: 1,
      idMapa: 5,
      idEquipeA: 3,
      idEquipeB: 4,
      melhorDe: 1,
      numeroPartida: 1,
      prorrogacao: false,
      partidaEncerrada: true,
      pontuacaoEquipeA: 16,
      pontuacaoEquipeB: 10,
      idEquipeVitoria: 3,
      idEquipeDerrota: 4,
    },
    {
      data: "2019-11-20 17:00:00",
      categoria: "LAN",
      idCampeonato: 1,
      idMapa: 1,
      idEquipeA: 5,
      idEquipeB: 6,
      melhorDe: 1,
      numeroPartida: 1,
      prorrogacao: false,
      partidaEncerrada: true,
      pontuacaoEquipeA: 16,
      pontuacaoEquipeB: 9,
      idEquipeVitoria: 5,
      idEquipeDerrota: 6,
    },
    {
      data: "2019-11-20 18:00:00",
      categoria: "LAN",
      idCampeonato: 1,
      idMapa: 2,
      idEquipeA: 7,
      idEquipeB: 8,
      melhorDe: 1,
      numeroPartida: 1,
      prorrogacao: false,
      partidaEncerrada: true,
      pontuacaoEquipeA: 16,
      pontuacaoEquipeB: 11,
      idEquipeVitoria: 7,
      idEquipeDerrota: 8,
    },
    {
      data: "2019-11-21 15:00:00",
      categoria: "LAN",
      idCampeonato: 1,
      idMapa: 1,
      idEquipeA: 1,
      idEquipeB: 3,
      melhorDe: 1,
      numeroPartida: 1,
      prorrogacao: false,
      partidaEncerrada: true,
      pontuacaoEquipeA: 16,
      pontuacaoEquipeB: 10,
      idEquipeVitoria: 1,
      idEquipeDerrota: 3,
    },
    {
      data: "2019-11-21 16:00:00",
      categoria: "LAN",
      idCampeonato: 1,
      idMapa: 7,
      idEquipeA: 5,
      idEquipeB: 7,
      melhorDe: 1,
      numeroPartida: 1,
      prorrogacao: false,
      partidaEncerrada: true,
      pontuacaoEquipeA: 16,
      pontuacaoEquipeB: 13,
      idEquipeVitoria: 5,
      idEquipeDerrota: 7,
    },
    {
      data: "2019-11-22 15:00:00",
      categoria: "LAN",
      idCampeonato: 1,
      idMapa: 4,
      idEquipeA: 1,
      idEquipeB: 5,
      melhorDe: 1,
      numeroPartida: 1,
      prorrogacao: false,
      partidaEncerrada: true,
      pontuacaoEquipeA: 16,
      pontuacaoEquipeB: 8,
      idEquipeVitoria: 1,
      idEquipeDerrota: 5,
    },
    {
      data: "2019-12-07 15:00:00",
      categoria: "LAN",
      idCampeonato: 2,
      idMapa: 2,
      idEquipeA: 1,
      idEquipeB: 2,
      melhorDe: 1,
      numeroPartida: 1,
      partidaEncerrada: false,
    },
    {
      data: "2019-12-07 16:00:00",
      categoria: "LAN",
      idCampeonato: 2,
      idMapa: 4,
      idEquipeA: 3,
      idEquipeB: 4,
      melhorDe: 1,
      numeroPartida: 1,
      partidaEncerrada: false,
    },
    {
      data: "2019-12-07 17:00:00",
      categoria: "LAN",
      idCampeonato: 2,
      idMapa: 3,
      idEquipeA: 5,
      idEquipeB: 6,
      melhorDe: 1,
      numeroPartida: 1,
      partidaEncerrada: false,
    },
    {
      data: "2019-12-07 18:00:00",
      categoria: "LAN",
      idCampeonato: 2,
      idMapa: 1,
      idEquipeA: 7,
      idEquipeB: 8,
      melhorDe: 1,
      numeroPartida: 1,
      partidaEncerrada: false,
    },
    {
      data: "2019-12-08 15:00:00",
      categoria: "LAN",
      idCampeonato: 2,
      idMapa: 6,
      idEquipeA: 1,
      idEquipeB: 3,
      melhorDe: 1,
      numeroPartida: 1,
      partidaEncerrada: false,
    },
    {
      data: "2019-12-08 16:00:00",
      categoria: "LAN",
      idCampeonato: 2,
      idMapa: 1,
      idEquipeA: 5,
      idEquipeB: 7,
      melhorDe: 1,
      numeroPartida: 1,
      partidaEncerrada: false,
    },
    {
      data: "2019-12-09 15:00:00",
      categoria: "LAN",
      idCampeonato: 2,
      idMapa: 3,
      idEquipeA: 1,
      idEquipeB: 5,
      melhorDe: 1,
      numeroPartida: 1,
      partidaEncerrada: false,
    }
  ]
}

module.exports = partidas